# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "b|ognik"
description: >-
  A place for fragments: notes, images, and half-formed thoughts.
  Picked up, kept, and arranged into something new.
  Broken and unfinished welcome.

url: "https://spiritedcarrot.github.io"
baseurl: ""

remote_theme: "jekyll/minima"

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - archive.md
  - comics.md
  - stuff-i-love.md

minima:
  skin: solarized-dark
  nav_pages:
    - archive.md
    - comics.md
    - stuff-i-love.md
  social_links:
    - title: GitHub
      icon: github
      url: "https://github.com/SpiritedCarrot"
  hide_site_feed_link: true

author: 
  name: "SpiritedCarrot"

license_name: "CC BY-NC 4.0"
license_url: "https://creativecommons.org/licenses/by-nc/4.0/"

kofi_url: "https://ko-fi.com/U7U11Q58JF"

markdown: kramdown
permalink: pretty

collections:
  comics:
    output: true
    permalink: /comics/:name/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

  - scope:
      path: ""
      type: comics
    values:
      layout: comic

sass:
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
  - .bundle

excerpt_separator: "<!--more-->"